languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Casual Survivors"
logo = "img/cs_logo.webp"
description = "Gaming News and Guides for Survivor Games"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "January 2, 2006"

[author]
  name = "Casual Survivors"
  image = "img/cs_logo.webp"
  headline = "Your ticket to safety."
  bio = "Where you come to survive."
